### PR TITLE
Support latest IDE version (2024.2)

### PR DESCRIPTION
**Pull request by Elhussein-Hamed**
Added the support for IDE version 2024.2.

### CODE REVIEW

**Comment by Elhussein-Hamed** [comment]
@robohorse Could you please check if anything else needs to be added to support versions 2024.2.*

**Review by robohorse — APPROVED** [review]
Really great job! 👍 Thanks a lot. I'll publish a new build soon

**Comment by robohorse** [comment]
hey @Elhussein-Hamed , you changes are live. Technically it should be supported out of the box as we have this [property](https://github.com/robohorse/RoboPOJOGenerator/blob/main/main/src/main/resources/META-INF/plugin.xml#L4) ... but let's see if we should define the latest IDE build as a target one 🤔 IDK honestly 🙈

**Comment by Elhussein-Hamed** [comment]
@robohorse Yes you are right. I can see that on the plugin page, it does not have an 'unitl build' version. Sorry I followed what I usually do with my plugin as I don't have 'until build' defined but it takes it to be the target IDE version so I thought that the same applies to your plugin.

That makes my changes unnecessary, so feel free to revert them if you wish.

Side note: My plugin depends on yours :) So thanks for this amazing plugin.

**Pull request merged**
